/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package theproject;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author monax
 */
public class COMPETITIONS extends javax.swing.JFrame {

    /**
     * Creates new form COMPETITIONS
     */
    public COMPETITIONS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        STUDENT_PANEL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PERSON = new javax.swing.JTable();
        STEP2 = new javax.swing.JPanel();
        InsertBtn = new javax.swing.JButton();
        AlterBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        STEP3 = new javax.swing.JPanel();
        STUDENT_ID = new javax.swing.JTextField();
        LESSON_ID = new javax.swing.JTextField();
        TEACHER_ID = new javax.swing.JTextField();
        PHACE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        STEP4 = new javax.swing.JPanel();
        CoursesBtn1 = new javax.swing.JButton();
        ExamBtn1 = new javax.swing.JButton();
        TtoLBtn1 = new javax.swing.JButton();
        CompBtn1 = new javax.swing.JButton();
        CHOISE = new javax.swing.JComboBox<>();
        QBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        STEP7 = new javax.swing.JPanel();
        output2 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        STUDENT_PANEL.setBackground(new java.awt.Color(51, 51, 51));

        PERSON.setBackground(new java.awt.Color(204, 204, 204));
        PERSON.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "TEACHER ID", "STUDENT ID", "LESSON ID", "PHACE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PERSON);

        STEP2.setBackground(new java.awt.Color(51, 51, 51));
        STEP2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 2   (choose action)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        InsertBtn.setBackground(new java.awt.Color(102, 102, 102));
        InsertBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        InsertBtn.setForeground(new java.awt.Color(255, 255, 255));
        InsertBtn.setText("INSERT");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });

        AlterBtn.setBackground(new java.awt.Color(102, 102, 102));
        AlterBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AlterBtn.setForeground(new java.awt.Color(255, 255, 255));
        AlterBtn.setText("ALTER");
        AlterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(102, 102, 102));
        DeleteBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP2Layout = new javax.swing.GroupLayout(STEP2);
        STEP2.setLayout(STEP2Layout);
        STEP2Layout.setHorizontalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertBtn)
                .addGap(81, 81, 81)
                .addComponent(DeleteBtn)
                .addGap(81, 81, 81)
                .addComponent(AlterBtn)
                .addContainerGap())
        );
        STEP2Layout.setVerticalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBtn)
                    .addComponent(AlterBtn)
                    .addComponent(DeleteBtn))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        STEP3.setBackground(new java.awt.Color(51, 51, 51));
        STEP3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 3  (let's type)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        STUDENT_ID.setBackground(new java.awt.Color(84, 84, 84));
        STUDENT_ID.setForeground(new java.awt.Color(204, 204, 204));
        STUDENT_ID.setText("STUDENT ID...");
        STUDENT_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        STUDENT_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                STUDENT_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                STUDENT_IDFocusLost(evt);
            }
        });
        STUDENT_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STUDENT_IDActionPerformed(evt);
            }
        });

        LESSON_ID.setBackground(new java.awt.Color(84, 84, 84));
        LESSON_ID.setForeground(new java.awt.Color(204, 204, 204));
        LESSON_ID.setText("LESSON ID...");
        LESSON_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LESSON ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        LESSON_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                LESSON_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                LESSON_IDFocusLost(evt);
            }
        });
        LESSON_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LESSON_IDActionPerformed(evt);
            }
        });

        TEACHER_ID.setBackground(new java.awt.Color(84, 84, 84));
        TEACHER_ID.setForeground(new java.awt.Color(204, 204, 204));
        TEACHER_ID.setText("TEACHER ID...");
        TEACHER_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TEACHER ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        TEACHER_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEACHER_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TEACHER_IDFocusLost(evt);
            }
        });
        TEACHER_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEACHER_IDActionPerformed(evt);
            }
        });

        PHACE.setBackground(new java.awt.Color(84, 84, 84));
        PHACE.setForeground(new java.awt.Color(204, 204, 204));
        PHACE.setText("PHACE...");
        PHACE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PHACE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PHACE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PHACEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PHACEFocusLost(evt);
            }
        });
        PHACE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PHACEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP3Layout = new javax.swing.GroupLayout(STEP3);
        STEP3.setLayout(STEP3Layout);
        STEP3Layout.setHorizontalGroup(
            STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addComponent(LESSON_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PHACE, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addComponent(TEACHER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(STUDENT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55))
        );
        STEP3Layout.setVerticalGroup(
            STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP3Layout.createSequentialGroup()
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(STUDENT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TEACHER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LESSON_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PHACE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RUN");
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        STEP4.setBackground(new java.awt.Color(51, 51, 51));
        STEP4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP  1   (choose table)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CoursesBtn1.setBackground(new java.awt.Color(102, 102, 102));
        CoursesBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CoursesBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CoursesBtn1.setText("COURSES");
        CoursesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesBtn1ActionPerformed(evt);
            }
        });

        ExamBtn1.setBackground(new java.awt.Color(102, 102, 102));
        ExamBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        ExamBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ExamBtn1.setText("EXAM RESULTS");
        ExamBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamBtn1ActionPerformed(evt);
            }
        });

        TtoLBtn1.setBackground(new java.awt.Color(102, 102, 102));
        TtoLBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        TtoLBtn1.setForeground(new java.awt.Color(255, 255, 255));
        TtoLBtn1.setText("TEACHER TO LESSON");
        TtoLBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtoLBtn1ActionPerformed(evt);
            }
        });

        CompBtn1.setBackground(new java.awt.Color(102, 102, 102));
        CompBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CompBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CompBtn1.setText("COMPETITIONS");
        CompBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompBtn1ActionPerformed(evt);
            }
        });

        CHOISE.setBackground(new java.awt.Color(102, 102, 102));
        CHOISE.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CHOISE.setForeground(new java.awt.Color(255, 255, 255));
        CHOISE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "TEACHER" }));
        CHOISE.setAlignmentX(CENTER_ALIGNMENT);
        CHOISE.setAlignmentY(CENTER_ALIGNMENT);
        CHOISE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CHOISE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOISEActionPerformed(evt);
            }
        });

        QBtn.setBackground(new java.awt.Color(102, 102, 102));
        QBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        QBtn.setForeground(new java.awt.Color(255, 255, 255));
        QBtn.setText("QUESTIONS");
        QBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QBtnActionPerformed(evt);
            }
        });

        LogBtn.setBackground(new java.awt.Color(102, 102, 102));
        LogBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("LOG");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP4Layout = new javax.swing.GroupLayout(STEP4);
        STEP4.setLayout(STEP4Layout);
        STEP4Layout.setHorizontalGroup(
            STEP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursesBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExamBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TtoLBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CHOISE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CompBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP4Layout.setVerticalGroup(
            STEP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP4Layout.createSequentialGroup()
                .addComponent(CHOISE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CoursesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ExamBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TtoLBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CompBtn1)
                .addGap(0, 0, 0)
                .addComponent(QBtn)
                .addGap(0, 0, 0)
                .addComponent(LogBtn)
                .addGap(0, 0, 0))
        );

        STEP7.setBackground(new java.awt.Color(51, 51, 51));
        STEP7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5), "OUTPUT ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout STEP7Layout = new javax.swing.GroupLayout(STEP7);
        STEP7.setLayout(STEP7Layout);
        STEP7Layout.setHorizontalGroup(
            STEP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(output2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP7Layout.setVerticalGroup(
            STEP7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(output2, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout STUDENT_PANELLayout = new javax.swing.GroupLayout(STUDENT_PANEL);
        STUDENT_PANEL.setLayout(STUDENT_PANELLayout);
        STUDENT_PANELLayout.setHorizontalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                .addComponent(STEP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(STEP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(STEP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(STEP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        STUDENT_PANELLayout.setVerticalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addComponent(STEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(STEP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(19, 19, 19)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addComponent(STEP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 19, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(STEP7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void AlterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void STUDENT_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STUDENT_IDFocusGained
        if(STUDENT_ID.getText().equals("STUDENT ID...")){
            STUDENT_ID.setText("");
        }
    }//GEN-LAST:event_STUDENT_IDFocusGained

    private void STUDENT_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STUDENT_IDFocusLost
        if(STUDENT_ID.getText().equals("")){
            STUDENT_ID.setText("STUDENT ID...");
        }
    }//GEN-LAST:event_STUDENT_IDFocusLost

    private void STUDENT_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STUDENT_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STUDENT_IDActionPerformed

    private void LESSON_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LESSON_IDFocusGained
        if(LESSON_ID.getText().equals("LESSON ID...")){
            LESSON_ID.setText("");
        }
    }//GEN-LAST:event_LESSON_IDFocusGained

    private void LESSON_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_LESSON_IDFocusLost
        if(LESSON_ID.getText().equals("")){
            LESSON_ID.setText("LESSON ID...");
        }
    }//GEN-LAST:event_LESSON_IDFocusLost

    private void LESSON_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LESSON_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LESSON_IDActionPerformed

    private void TEACHER_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEACHER_IDFocusGained
        if(TEACHER_ID.getText().equals("TEACHER ID...")){
            TEACHER_ID.setText("");
        }
    }//GEN-LAST:event_TEACHER_IDFocusGained

    private void TEACHER_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEACHER_IDFocusLost
        if(TEACHER_ID.getText().equals("")){
            TEACHER_ID.setText("TEACHER ID...");
        }
    }//GEN-LAST:event_TEACHER_IDFocusLost

    private void TEACHER_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEACHER_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEACHER_IDActionPerformed

    private void PHACEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PHACEFocusGained
        if(PHACE.getText().equals("PHACE...")){
            PHACE.setText("");
        }
    }//GEN-LAST:event_PHACEFocusGained

    private void PHACEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PHACEFocusLost
        if(PHACE.getText().equals("")){
            PHACE.setText("PHACE...");
        }
    }//GEN-LAST:event_PHACEFocusLost

    private void PHACEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PHACEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PHACEActionPerformed

    private void CoursesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesBtn1ActionPerformed
        COURSES courses = new COURSES();
        courses.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoursesBtn1ActionPerformed

    private void ExamBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamBtn1ActionPerformed
        EXAM_RESULTS exam_res = new EXAM_RESULTS();
        exam_res.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExamBtn1ActionPerformed

    private void TtoLBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtoLBtn1ActionPerformed
        TEACHER_TO_LESSON teacher_to_lesson = new TEACHER_TO_LESSON();
        teacher_to_lesson.setVisible(true);
        dispose();
    }//GEN-LAST:event_TtoLBtn1ActionPerformed

    private void CompBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompBtn1ActionPerformed
        COMPETITIONS competitions = new COMPETITIONS();
        competitions.setVisible(true);
        dispose();
    }//GEN-LAST:event_CompBtn1ActionPerformed

    private void CHOISEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOISEActionPerformed
        String choise=CHOISE.getSelectedItem().toString();
        TEACHER teacher = new TEACHER();
        STUDENT student = new STUDENT();
        if(choise.equals("TEACHER"))
        {
            teacher.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_CHOISEActionPerformed

    private void QBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QBtnActionPerformed
        QUESTIONS questions = new QUESTIONS();
        questions.setVisible(true);
        dispose();
    }//GEN-LAST:event_QBtnActionPerformed

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        LOG log = new LOG();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        for(int i=0;i<=2;i++){
             for(int j=0;j<=3;j++){
                    PERSON.setValueAt("",i,j);
           }
           }
            ArrayList<String> list= new ArrayList<String>();
           try {
               list = TheProject.display_comp();
           } catch (Exception ex) {
               Logger.getLogger(COMPETITIONS.class.getName()).log(Level.SEVERE, null, ex);
           }
          int k=0;
           for(int i=0;i<=2;i++){
             for(int j=0;j<=3;j++){
                 if(list.get(k)!=null)
                    PERSON.setValueAt(list.get(k).toString(),i,j);
                k=k+1;
           }
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(COMPETITIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(COMPETITIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(COMPETITIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(COMPETITIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new COMPETITIONS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterBtn;
    private javax.swing.JComboBox<String> CHOISE;
    private javax.swing.JButton CompBtn1;
    private javax.swing.JButton CoursesBtn1;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton ExamBtn1;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JTextField LESSON_ID;
    private javax.swing.JButton LogBtn;
    private javax.swing.JTable PERSON;
    private javax.swing.JTextField PHACE;
    private javax.swing.JButton QBtn;
    private javax.swing.JPanel STEP2;
    private javax.swing.JPanel STEP3;
    private javax.swing.JPanel STEP4;
    private javax.swing.JPanel STEP7;
    private javax.swing.JTextField STUDENT_ID;
    private javax.swing.JPanel STUDENT_PANEL;
    private javax.swing.JTextField TEACHER_ID;
    private javax.swing.JButton TtoLBtn1;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextArea output2;
    // End of variables declaration//GEN-END:variables
}
