/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package theproject;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author monax
 */
public class LOG extends javax.swing.JFrame {
 ArrayList<String> list= new ArrayList<String>();
  int length;
    /**
     * Creates new form LOG
     */
    public LOG() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        STUDENT_PANEL = new javax.swing.JPanel();
        STEP2 = new javax.swing.JPanel();
        Results = new java.awt.TextArea();
        STEP4 = new javax.swing.JPanel();
        CoursesBtn1 = new javax.swing.JButton();
        ExamBtn1 = new javax.swing.JButton();
        TtoLBtn1 = new javax.swing.JButton();
        CompBtn1 = new javax.swing.JButton();
        CHOISE = new javax.swing.JComboBox<>();
        QBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        display = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        STUDENT_PANEL.setBackground(new java.awt.Color(51, 51, 51));

        STEP2.setBackground(new java.awt.Color(51, 51, 51));
        STEP2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3), "THE LOG OF ' TEACHERS TO LESSON '", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        Results.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Results.setEditable(false);
        Results.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        Results.setName("LogTextArea"); // NOI18N
        Results.setText("Probably NO changes yet...");

        javax.swing.GroupLayout STEP2Layout = new javax.swing.GroupLayout(STEP2);
        STEP2.setLayout(STEP2Layout);
        STEP2Layout.setHorizontalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Results, javax.swing.GroupLayout.DEFAULT_SIZE, 805, Short.MAX_VALUE)
        );
        STEP2Layout.setVerticalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Results, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );

        STEP4.setBackground(new java.awt.Color(51, 51, 51));
        STEP4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP  1   (choose table)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CoursesBtn1.setBackground(new java.awt.Color(102, 102, 102));
        CoursesBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CoursesBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CoursesBtn1.setText("COURSES");
        CoursesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesBtn1ActionPerformed(evt);
            }
        });

        ExamBtn1.setBackground(new java.awt.Color(102, 102, 102));
        ExamBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        ExamBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ExamBtn1.setText("EXAM RESULTS");
        ExamBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamBtn1ActionPerformed(evt);
            }
        });

        TtoLBtn1.setBackground(new java.awt.Color(102, 102, 102));
        TtoLBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        TtoLBtn1.setForeground(new java.awt.Color(255, 255, 255));
        TtoLBtn1.setText("TEACHER TO LESSON");
        TtoLBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtoLBtn1ActionPerformed(evt);
            }
        });

        CompBtn1.setBackground(new java.awt.Color(102, 102, 102));
        CompBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CompBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CompBtn1.setText("COMPETITIONS");
        CompBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompBtn1ActionPerformed(evt);
            }
        });

        CHOISE.setBackground(new java.awt.Color(102, 102, 102));
        CHOISE.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CHOISE.setForeground(new java.awt.Color(255, 255, 255));
        CHOISE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "TEACHER" }));
        CHOISE.setAlignmentX(CENTER_ALIGNMENT);
        CHOISE.setAlignmentY(CENTER_ALIGNMENT);
        CHOISE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CHOISE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOISEActionPerformed(evt);
            }
        });

        QBtn.setBackground(new java.awt.Color(102, 102, 102));
        QBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        QBtn.setForeground(new java.awt.Color(255, 255, 255));
        QBtn.setText("QUESTIONS");
        QBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QBtnActionPerformed(evt);
            }
        });

        LogBtn.setBackground(new java.awt.Color(102, 102, 102));
        LogBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("LOG");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP4Layout = new javax.swing.GroupLayout(STEP4);
        STEP4.setLayout(STEP4Layout);
        STEP4Layout.setHorizontalGroup(
            STEP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursesBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExamBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TtoLBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CHOISE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CompBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP4Layout.setVerticalGroup(
            STEP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP4Layout.createSequentialGroup()
                .addComponent(CHOISE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CoursesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ExamBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TtoLBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CompBtn1)
                .addGap(0, 0, 0)
                .addComponent(QBtn)
                .addGap(0, 0, 0)
                .addComponent(LogBtn)
                .addGap(0, 0, 0))
        );

        display.setBackground(new java.awt.Color(102, 102, 102));
        display.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setText("DISPLAY");
        display.setAlignmentY(1.0F);
        display.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STUDENT_PANELLayout = new javax.swing.GroupLayout(STUDENT_PANEL);
        STUDENT_PANEL.setLayout(STUDENT_PANELLayout);
        STUDENT_PANELLayout.setHorizontalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addComponent(STEP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(135, 135, 135)
                        .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(STEP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        STUDENT_PANELLayout.setVerticalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(STEP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(display, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(STEP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CoursesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesBtn1ActionPerformed
        COURSES courses = new COURSES();
        courses.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoursesBtn1ActionPerformed

    private void ExamBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamBtn1ActionPerformed
        EXAM_RESULTS exam_res = new EXAM_RESULTS();
        exam_res.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExamBtn1ActionPerformed

    private void TtoLBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtoLBtn1ActionPerformed
        TEACHER_TO_LESSON teacher_to_lesson = new TEACHER_TO_LESSON();
        teacher_to_lesson.setVisible(true);
        dispose();
    }//GEN-LAST:event_TtoLBtn1ActionPerformed

    private void CompBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompBtn1ActionPerformed
        COMPETITIONS competitions = new COMPETITIONS();
        competitions.setVisible(true);
        dispose();
    }//GEN-LAST:event_CompBtn1ActionPerformed

    private void CHOISEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOISEActionPerformed
        String choise=CHOISE.getSelectedItem().toString();
        TEACHER teacher = new TEACHER();
        STUDENT student = new STUDENT();
        if(choise.equals("TEACHER"))
        {
            teacher.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_CHOISEActionPerformed

    private void QBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QBtnActionPerformed
        QUESTIONS questions = new QUESTIONS();
        questions.setVisible(true);
        dispose();
    }//GEN-LAST:event_QBtnActionPerformed

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        LOG log = new LOG();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogBtnActionPerformed

    private void displayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayActionPerformed
        Results.setText("");    
        try {
            length=TheProject.ttl_count()-1;
        } catch (Exception ex) {
            Logger.getLogger(TEACHER_TO_LESSON.class.getName()).log(Level.SEVERE, null, ex);
        }  
        ArrayList<String> list= new ArrayList<String>();
        try {
            list = TheProject.display_lf();
        } catch (Exception ex) {
            Logger.getLogger(LOG.class.getName()).log(Level.SEVERE, null, ex);
        }
        Iterator i=list.iterator();
        int k=0;
        try{
            while(i.hasNext()){
                if(list.get(k)!=null)
                    Results.setText(Results.getText()+" "+list.get(k).toString());
                k=k+1;
            }
        }catch(IndexOutOfBoundsException e){
            System.out.print("");
        }
    }//GEN-LAST:event_displayActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOG.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOG().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CHOISE;
    private javax.swing.JButton CompBtn1;
    private javax.swing.JButton CoursesBtn1;
    private javax.swing.JButton ExamBtn1;
    private javax.swing.JButton LogBtn;
    private javax.swing.JButton QBtn;
    private java.awt.TextArea Results;
    private javax.swing.JPanel STEP2;
    private javax.swing.JPanel STEP4;
    private javax.swing.JPanel STUDENT_PANEL;
    private javax.swing.JButton TtoLBtn1;
    private javax.swing.JButton display;
    // End of variables declaration//GEN-END:variables
}
