/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package theproject;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author monax
 */
public class QUESTIONS extends javax.swing.JFrame {
    ArrayList<String> list= new ArrayList<String>();
    int choise=0;
    String Sanswer=null;
    double Numanswer=0;
    int intanswer=0;

    String gr;
    
    
    public QUESTIONS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        STUDENT_PANEL = new javax.swing.JPanel();
        STEP2 = new javax.swing.JPanel();
        Q1 = new javax.swing.JRadioButton();
        Q1Ans = new javax.swing.JTextField();
        Q2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        Q21Ans = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Q3 = new javax.swing.JRadioButton();
        Q3Ans = new javax.swing.JTextField();
        Q4 = new javax.swing.JRadioButton();
        Q4Ans = new javax.swing.JTextField();
        Q5 = new javax.swing.JRadioButton();
        Q51Ans = new javax.swing.JTextField();
        Q52Ans = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Q6 = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        Q61Ans = new javax.swing.JComboBox<>();
        Q62Ans = new javax.swing.JComboBox<>();
        Q7 = new javax.swing.JRadioButton();
        Q7Ans = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Q8 = new javax.swing.JRadioButton();
        Q8Ans = new javax.swing.JTextField();
        Q9 = new javax.swing.JRadioButton();
        Q91Ans = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Q92Ans = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        Q10 = new javax.swing.JRadioButton();
        Q10Ans = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        Q61Ans1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        STEP4 = new javax.swing.JPanel();
        CoursesBtn1 = new javax.swing.JButton();
        ExamBtn1 = new javax.swing.JButton();
        TtoLBtn1 = new javax.swing.JButton();
        CompBtn1 = new javax.swing.JButton();
        CHOISE = new javax.swing.JComboBox<>();
        QBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        Results = new java.awt.TextArea();
        error = new java.awt.TextArea();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        STUDENT_PANEL.setBackground(new java.awt.Color(51, 51, 51));

        STEP2.setBackground(new java.awt.Color(51, 51, 51));
        STEP2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 2   (choose question)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        buttonGroup1.add(Q1);
        Q1.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q1.setForeground(new java.awt.Color(255, 255, 255));
        Q1.setText("How many students have a grade lower than 17 in the subject");
        Q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1ActionPerformed(evt);
            }
        });

        Q1Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q1Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q1Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q1AnsActionPerformed(evt);
            }
        });

        buttonGroup1.add(Q2);
        Q2.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q2.setForeground(new java.awt.Color(255, 255, 255));
        Q2.setText("Which teachers have a salary lower than ");
        Q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("€, and have gone  in a  competition ?");

        Q21Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q21Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q21Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q21AnsActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("and have gone to a competition?");

        buttonGroup1.add(Q3);
        Q3.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q3.setForeground(new java.awt.Color(255, 255, 255));
        Q3.setText("Which female teachers do the subject");
        Q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3ActionPerformed(evt);
            }
        });

        Q3Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q3Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q3Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q3AnsActionPerformed(evt);
            }
        });

        buttonGroup1.add(Q4);
        Q4.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q4.setForeground(new java.awt.Color(255, 255, 255));
        Q4.setText("Which students have a grade bigger (>) or equal (=) to  ");
        Q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4ActionPerformed(evt);
            }
        });

        Q4Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q4Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q4Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q4AnsActionPerformed(evt);
            }
        });

        buttonGroup1.add(Q5);
        Q5.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q5.setForeground(new java.awt.Color(255, 255, 255));
        Q5.setText("Which teachers, with at least ");
        Q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q5ActionPerformed(evt);
            }
        });

        Q51Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q51Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q51Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q51AnsActionPerformed(evt);
            }
        });

        Q52Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q52Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q52Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q52AnsActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("€ salary, teach at least  ");

        jLabel6.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("subjects");

        buttonGroup1.add(Q6);
        Q6.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q6.setForeground(new java.awt.Color(255, 255, 255));
        Q6.setText("How many teachers that are ");
        Q6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q6ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText(" a subject with \"final exams\"");

        Q61Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q61Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q61Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));

        Q62Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q62Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q62Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "do", "are not doing" }));
        Q62Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q62AnsActionPerformed(evt);
            }
        });

        buttonGroup1.add(Q7);
        Q7.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q7.setForeground(new java.awt.Color(255, 255, 255));
        Q7.setText("How many times has the teacher/student with id :");
        Q7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7ActionPerformed(evt);
            }
        });

        Q7Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q7Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q7Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q7AnsActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("gone to competitions?");

        buttonGroup1.add(Q8);
        Q8.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q8.setForeground(new java.awt.Color(255, 255, 255));
        Q8.setText("How many people");
        Q8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q8ActionPerformed(evt);
            }
        });

        Q8Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q8Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q8Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q8AnsActionPerformed(evt);
            }
        });

        buttonGroup1.add(Q9);
        Q9.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q9.setForeground(new java.awt.Color(255, 255, 255));
        Q9.setText("How many");
        Q9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q9ActionPerformed(evt);
            }
        });

        Q91Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q91Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q91Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "First class of secondary school", "Second class of secondary school", "Third class of secondary school" }));
        Q91Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q91AnsActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("students, does the ");

        Q92Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q92Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q92Ans.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        Q92Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q92AnsActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(" class of secondary school (gymnasiou) have?");

        buttonGroup1.add(Q10);
        Q10.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        Q10.setForeground(new java.awt.Color(255, 255, 255));
        Q10.setText("Which student/s has the highest and the lowest grade in the subject : ");
        Q10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q10ActionPerformed(evt);
            }
        });

        Q10Ans.setBackground(new java.awt.Color(102, 102, 102));
        Q10Ans.setForeground(new java.awt.Color(255, 255, 255));
        Q10Ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Q10AnsActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Bahnschrift", 1, 13)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(" are there with the surname : ");

        Q61Ans1.setBackground(new java.awt.Color(102, 102, 102));
        Q61Ans1.setForeground(new java.awt.Color(255, 255, 255));
        Q61Ans1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "student", "teacher", "both" }));

        javax.swing.GroupLayout STEP2Layout = new javax.swing.GroupLayout(STEP2);
        STEP2.setLayout(STEP2Layout);
        STEP2Layout.setHorizontalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STEP2Layout.createSequentialGroup()
                        .addComponent(Q2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Q21Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(STEP2Layout.createSequentialGroup()
                        .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(STEP2Layout.createSequentialGroup()
                                        .addComponent(Q3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Q3Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Q4, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Q1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(STEP2Layout.createSequentialGroup()
                                        .addComponent(Q4Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel3))
                                    .addComponent(Q1Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addComponent(Q10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q10Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addComponent(Q9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q92Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q91Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel10))
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addComponent(Q8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q61Ans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel13)
                                .addGap(4, 4, 4)
                                .addComponent(Q8Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addComponent(Q7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q7Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8))
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addComponent(Q6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q61Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q62Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(STEP2Layout.createSequentialGroup()
                                .addComponent(Q5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q51Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Q52Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addContainerGap(53, Short.MAX_VALUE))))
        );
        STEP2Layout.setVerticalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q1)
                    .addComponent(Q1Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q2)
                    .addComponent(Q21Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q3)
                    .addComponent(Q3Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q4)
                    .addComponent(Q4Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q5)
                    .addComponent(Q51Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(Q52Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(24, 24, 24)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q6)
                    .addComponent(Q61Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q62Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q7)
                    .addComponent(Q7Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q8)
                    .addComponent(Q61Ans1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(Q8Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q9)
                    .addComponent(Q92Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(Q91Ans, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Q10Ans, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Q10))
                .addContainerGap())
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RUN");
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        STEP4.setBackground(new java.awt.Color(51, 51, 51));
        STEP4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP  1   (choose table)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CoursesBtn1.setBackground(new java.awt.Color(102, 102, 102));
        CoursesBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CoursesBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CoursesBtn1.setText("COURSES");
        CoursesBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesBtn1ActionPerformed(evt);
            }
        });

        ExamBtn1.setBackground(new java.awt.Color(102, 102, 102));
        ExamBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        ExamBtn1.setForeground(new java.awt.Color(255, 255, 255));
        ExamBtn1.setText("EXAM RESULTS");
        ExamBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamBtn1ActionPerformed(evt);
            }
        });

        TtoLBtn1.setBackground(new java.awt.Color(102, 102, 102));
        TtoLBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        TtoLBtn1.setForeground(new java.awt.Color(255, 255, 255));
        TtoLBtn1.setText("TEACHER TO LESSON");
        TtoLBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtoLBtn1ActionPerformed(evt);
            }
        });

        CompBtn1.setBackground(new java.awt.Color(102, 102, 102));
        CompBtn1.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CompBtn1.setForeground(new java.awt.Color(255, 255, 255));
        CompBtn1.setText("COMPETITIONS");
        CompBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompBtn1ActionPerformed(evt);
            }
        });

        CHOISE.setBackground(new java.awt.Color(102, 102, 102));
        CHOISE.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CHOISE.setForeground(new java.awt.Color(255, 255, 255));
        CHOISE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "TEACHER" }));
        CHOISE.setAlignmentX(CENTER_ALIGNMENT);
        CHOISE.setAlignmentY(CENTER_ALIGNMENT);
        CHOISE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CHOISE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOISEActionPerformed(evt);
            }
        });

        QBtn.setBackground(new java.awt.Color(102, 102, 102));
        QBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        QBtn.setForeground(new java.awt.Color(255, 255, 255));
        QBtn.setText("QUESTIONS");
        QBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QBtnActionPerformed(evt);
            }
        });

        LogBtn.setBackground(new java.awt.Color(102, 102, 102));
        LogBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("LOG");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP4Layout = new javax.swing.GroupLayout(STEP4);
        STEP4.setLayout(STEP4Layout);
        STEP4Layout.setHorizontalGroup(
            STEP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursesBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExamBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TtoLBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CHOISE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CompBtn1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP4Layout.setVerticalGroup(
            STEP4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP4Layout.createSequentialGroup()
                .addComponent(CHOISE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CoursesBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ExamBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TtoLBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CompBtn1)
                .addGap(0, 0, 0)
                .addComponent(QBtn)
                .addGap(0, 0, 0)
                .addComponent(LogBtn)
                .addGap(0, 0, 0))
        );

        Results.setName("Results"); // NOI18N

        jLabel11.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("RESULTS");

        jLabel12.setFont(new java.awt.Font("Bahnschrift", 1, 30)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ERROR DISPLAY");

        javax.swing.GroupLayout STUDENT_PANELLayout = new javax.swing.GroupLayout(STUDENT_PANEL);
        STUDENT_PANEL.setLayout(STUDENT_PANELLayout);
        STUDENT_PANELLayout.setHorizontalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(STEP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(STEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STUDENT_PANELLayout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addGap(130, 130, 130))))
                            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                                .addGap(473, 473, 473)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addContainerGap())
        );
        STUDENT_PANELLayout.setVerticalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addComponent(STEP4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(STEP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addGap(51, 51, 51)
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Results, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(error, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(221, 221, 221))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        LOG log = new LOG();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogBtnActionPerformed

    private void QBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QBtnActionPerformed
        QUESTIONS questions = new QUESTIONS();
        questions.setVisible(true);
        dispose();
    }//GEN-LAST:event_QBtnActionPerformed

    private void CHOISEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOISEActionPerformed
        String choise=CHOISE.getSelectedItem().toString();
        TEACHER teacher = new TEACHER();
        STUDENT student = new STUDENT();
        if(choise.equals("TEACHER"))
        {
            teacher.setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_CHOISEActionPerformed

    private void CompBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompBtn1ActionPerformed
        COMPETITIONS competitions = new COMPETITIONS();
        competitions.setVisible(true);
        dispose();
    }//GEN-LAST:event_CompBtn1ActionPerformed

    private void TtoLBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtoLBtn1ActionPerformed
        TEACHER_TO_LESSON teacher_to_lesson = new TEACHER_TO_LESSON();
        teacher_to_lesson.setVisible(true);
        dispose();
    }//GEN-LAST:event_TtoLBtn1ActionPerformed

    private void ExamBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamBtn1ActionPerformed
        EXAM_RESULTS exam_res = new EXAM_RESULTS();
        exam_res.setVisible(true);
        dispose();
    }//GEN-LAST:event_ExamBtn1ActionPerformed

    private void CoursesBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesBtn1ActionPerformed
        COURSES courses = new COURSES();
        courses.setVisible(true);
        dispose();
    }//GEN-LAST:event_CoursesBtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        switch (choise) {
            case 0 -> error.setText("YOU DIDN'T CHOOSE SOMETHING FROM STEP 2... PLEASE CHOOSE");
            case 1 -> {
                Results.setText("");
                intanswer=Integer.parseInt(Q1Ans.getText());
                
            try {
                Sanswer=TheProject.AgoriaMeMo(intanswer);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);       
            }
            Results.setText(Sanswer);
            }
            case 2 -> {
                Results.setText("");
                int a21=Integer.parseInt(Q21Ans.getText());

            try {
                list=TheProject.getteacherssalarycomp(a21);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }
            Iterator i=list.iterator();
        int k=0;
        try{
            while(i.hasNext()){
                if(list.get(k)!=null)
                    Results.setText(Results.getText()+" "+list.get(k).toString());
                k=k+1;
            }
        }catch(IndexOutOfBoundsException e){
            System.out.print("");
        }
            }
            case 3 -> {
                Results.setText("");
            int a3=Integer.parseInt(Q3Ans.getText());
            try {
                list=TheProject.gynaika_mathimatika(a3);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }
            Iterator i=list.iterator();
        int k=0;
        try{
            while(i.hasNext()){
                if(list.get(k)!=null)
                    Results.setText(Results.getText()+" "+list.get(k).toString()+"\n");
                k=k+1;
            }
        }catch(IndexOutOfBoundsException e){
            System.out.print("");
        }
            }
            case 4 -> {
                Results.setText("");
            double a4=Double.parseDouble(Q4Ans.getText());
            try {
             list=TheProject.kalo_mo_comp(a4);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }
            Iterator i=list.iterator();
        int k=0;
        try{
            while(i.hasNext()){
                if(list.get(k)!=null)
                    Results.setText(Results.getText()+" "+list.get(k).toString()+"\n");
                k=k+1;
            }
        }catch(IndexOutOfBoundsException e){
            System.out.print("");
        }
            }
            case 5 -> {
                Results.setText("");
                int a51=Integer.parseInt(Q51Ans.getText());
                int a52=Integer.parseInt(Q52Ans.getText());
                
                System.out.print(a51+""+a52);
                
            try {
                list=TheProject.kath_salary_and_lessons(a51,a52);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }
            Iterator i=list.iterator();
            int k=0;
            try{
                while(i.hasNext()){
                    if(list.get(k)!=null)
                        Results.setText(Results.getText()+" "+list.get(k).toString()+"\n");
                    k=k+1;
                }
            }catch(IndexOutOfBoundsException e){
                System.out.print("");
            }
            }
            case 6 -> {
                Results.setText("");
           String a61=(String)Q61Ans.getSelectedItem();
           String a62=(String)Q62Ans.getSelectedItem();

            try {
                Sanswer=TheProject.kathigiti_and_exam(a61, a62);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }

            Results.setText(Sanswer);
            }
            case 7 -> {
                int a7=Integer.parseInt(Q7Ans.getText());
            try {
                gr=TheProject.poioi_kai_poses(a7);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }
            Results.setText(gr);
            }
            case 8 -> {
                Results.setText("");
                String a81=(String)Q61Ans1.getSelectedItem();
                String a82=(String)Q8Ans.getText();
                try {
                    Sanswer=TheProject.posoi_me_epitheto(a81,a82);
                } catch (Exception ex) {
                    Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
                }
                Results.setText(Sanswer);
            }
            case 9 -> {
                Results.setText("");
                String a91=(String)Q91Ans.getSelectedItem();
                String a92=(String)Q92Ans.getSelectedItem();
                
            try {
                Sanswer=TheProject.posous_filo_apo_taxi(a91, a92);
            } catch (Exception ex) {
                Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
            }
            Results.setText(Sanswer);
                
            }
            case 10 -> {
                Results.setText("");
                intanswer=Integer.parseInt(Q10Ans.getText());
                ArrayList<String> list= new ArrayList<String>();
                try {
                    list = TheProject.worst_and_best(intanswer);
                }catch (Exception ex) {
                    Logger.getLogger(QUESTIONS.class.getName()).log(Level.SEVERE, null, ex);
                }
                Iterator i=list.iterator();
                int k=0;
                try{
                    while(i.hasNext()){
                        if(list.get(k)!=null)
                            Results.setText(Results.getText()+" "+list.get(k).toString()+"\n");
                        System.out.println(list.get(k).toString());
                        k=k+1;
                    }
                }catch(IndexOutOfBoundsException e){
                    System.out.print("");
                }
            }
            default -> {
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Q10AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q10AnsActionPerformed

    }//GEN-LAST:event_Q10AnsActionPerformed

    private void Q10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q10ActionPerformed
        choise=10;
    }//GEN-LAST:event_Q10ActionPerformed

    private void Q92AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q92AnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q92AnsActionPerformed

    private void Q91AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q91AnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q91AnsActionPerformed

    private void Q9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q9ActionPerformed
        choise=9;
    }//GEN-LAST:event_Q9ActionPerformed

    private void Q8AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q8AnsActionPerformed

    }//GEN-LAST:event_Q8AnsActionPerformed

    private void Q8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q8ActionPerformed
        choise=8;
    }//GEN-LAST:event_Q8ActionPerformed

    private void Q7AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q7AnsActionPerformed

    }//GEN-LAST:event_Q7AnsActionPerformed

    private void Q7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q7ActionPerformed
        choise=7;
    }//GEN-LAST:event_Q7ActionPerformed

    private void Q62AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q62AnsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Q62AnsActionPerformed

    private void Q6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q6ActionPerformed
        choise=6;
    }//GEN-LAST:event_Q6ActionPerformed

    private void Q52AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q52AnsActionPerformed

    }//GEN-LAST:event_Q52AnsActionPerformed

    private void Q51AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q51AnsActionPerformed

    }//GEN-LAST:event_Q51AnsActionPerformed

    private void Q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q5ActionPerformed
        choise=5;
    }//GEN-LAST:event_Q5ActionPerformed

    private void Q4AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4AnsActionPerformed

    }//GEN-LAST:event_Q4AnsActionPerformed

    private void Q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q4ActionPerformed
        choise=4;
    }//GEN-LAST:event_Q4ActionPerformed

    private void Q3AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3AnsActionPerformed

    }//GEN-LAST:event_Q3AnsActionPerformed

    private void Q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q3ActionPerformed
        choise=3;
    }//GEN-LAST:event_Q3ActionPerformed

    private void Q21AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q21AnsActionPerformed

    }//GEN-LAST:event_Q21AnsActionPerformed

    private void Q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q2ActionPerformed
        choise=2;
    }//GEN-LAST:event_Q2ActionPerformed

    private void Q1AnsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1AnsActionPerformed

    }//GEN-LAST:event_Q1AnsActionPerformed

    private void Q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Q1ActionPerformed
        choise=1;
    }//GEN-LAST:event_Q1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QUESTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QUESTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QUESTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QUESTIONS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QUESTIONS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CHOISE;
    private javax.swing.JButton CompBtn1;
    private javax.swing.JButton CoursesBtn1;
    private javax.swing.JButton ExamBtn1;
    private javax.swing.JButton LogBtn;
    private javax.swing.JRadioButton Q1;
    private javax.swing.JRadioButton Q10;
    private javax.swing.JTextField Q10Ans;
    private javax.swing.JTextField Q1Ans;
    private javax.swing.JRadioButton Q2;
    private javax.swing.JTextField Q21Ans;
    private javax.swing.JRadioButton Q3;
    private javax.swing.JTextField Q3Ans;
    private javax.swing.JRadioButton Q4;
    private javax.swing.JTextField Q4Ans;
    private javax.swing.JRadioButton Q5;
    private javax.swing.JTextField Q51Ans;
    private javax.swing.JTextField Q52Ans;
    private javax.swing.JRadioButton Q6;
    private javax.swing.JComboBox<String> Q61Ans;
    private javax.swing.JComboBox<String> Q61Ans1;
    private javax.swing.JComboBox<String> Q62Ans;
    private javax.swing.JRadioButton Q7;
    private javax.swing.JTextField Q7Ans;
    private javax.swing.JRadioButton Q8;
    private javax.swing.JTextField Q8Ans;
    private javax.swing.JRadioButton Q9;
    private javax.swing.JComboBox<String> Q91Ans;
    private javax.swing.JComboBox<String> Q92Ans;
    private javax.swing.JButton QBtn;
    private java.awt.TextArea Results;
    private javax.swing.JPanel STEP2;
    private javax.swing.JPanel STEP4;
    private javax.swing.JPanel STUDENT_PANEL;
    private javax.swing.JButton TtoLBtn1;
    private javax.swing.ButtonGroup buttonGroup1;
    private java.awt.TextArea error;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
