package theproject;


import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;

public class STUDENT extends javax.swing.JFrame {
    ArrayList<String> list= new ArrayList<String>();
    int choise = 0;
    String name;
    String bdate;
    String sex;
    String taxi;
    int id=000;
    String x=null;
    
    public STUDENT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        STUDENT_PANEL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        STEP1 = new javax.swing.JPanel();
        CoursesBtn = new javax.swing.JButton();
        ExamBtn = new javax.swing.JButton();
        TtoLBtn = new javax.swing.JButton();
        CompBtn = new javax.swing.JButton();
        CHOISE = new javax.swing.JComboBox<>();
        QBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        STEP2 = new javax.swing.JPanel();
        InsertBtn = new javax.swing.JButton();
        AlterBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        STEP3 = new javax.swing.JPanel();
        PNAME = new javax.swing.JTextField();
        BIRTHDATE = new javax.swing.JTextField();
        SEX = new javax.swing.JTextField();
        STUDENT_ID = new javax.swing.JTextField();
        grade = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        STEP5 = new javax.swing.JPanel();
        output = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 51));

        STUDENT_PANEL.setBackground(new java.awt.Color(51, 51, 51));

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PERSON NAME", "BIRTHDAY", "SEX", "STUDENT ID", "M.O"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable);

        STEP1.setBackground(new java.awt.Color(51, 51, 51));
        STEP1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP  1   (choose table)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CoursesBtn.setBackground(new java.awt.Color(102, 102, 102));
        CoursesBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CoursesBtn.setForeground(new java.awt.Color(255, 255, 255));
        CoursesBtn.setText("COURSES");
        CoursesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesBtnActionPerformed(evt);
            }
        });

        ExamBtn.setBackground(new java.awt.Color(102, 102, 102));
        ExamBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        ExamBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExamBtn.setText("EXAM RESULTS");
        ExamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamBtnActionPerformed(evt);
            }
        });

        TtoLBtn.setBackground(new java.awt.Color(102, 102, 102));
        TtoLBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        TtoLBtn.setForeground(new java.awt.Color(255, 255, 255));
        TtoLBtn.setText("TEACHER TO LESSON");
        TtoLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtoLBtnActionPerformed(evt);
            }
        });

        CompBtn.setBackground(new java.awt.Color(102, 102, 102));
        CompBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CompBtn.setForeground(new java.awt.Color(255, 255, 255));
        CompBtn.setText("COMPETITIONS");
        CompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompBtnActionPerformed(evt);
            }
        });

        CHOISE.setBackground(new java.awt.Color(102, 102, 102));
        CHOISE.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CHOISE.setForeground(new java.awt.Color(255, 255, 255));
        CHOISE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "STUDENT", "TEACHER" }));
        CHOISE.setAlignmentX(CENTER_ALIGNMENT);
        CHOISE.setAlignmentY(CENTER_ALIGNMENT);
        CHOISE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CHOISE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOISEActionPerformed(evt);
            }
        });

        QBtn.setBackground(new java.awt.Color(102, 102, 102));
        QBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        QBtn.setForeground(new java.awt.Color(255, 255, 255));
        QBtn.setText("QUESTIONS");
        QBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QBtnActionPerformed(evt);
            }
        });

        LogBtn.setBackground(new java.awt.Color(102, 102, 102));
        LogBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("LOG");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP1Layout = new javax.swing.GroupLayout(STEP1);
        STEP1.setLayout(STEP1Layout);
        STEP1Layout.setHorizontalGroup(
            STEP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TtoLBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CHOISE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CompBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP1Layout.setVerticalGroup(
            STEP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP1Layout.createSequentialGroup()
                .addComponent(CHOISE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CoursesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ExamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TtoLBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CompBtn)
                .addGap(0, 0, 0)
                .addComponent(QBtn)
                .addGap(0, 0, 0)
                .addComponent(LogBtn)
                .addGap(0, 0, 0))
        );

        STEP2.setBackground(new java.awt.Color(51, 51, 51));
        STEP2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 2   (choose action)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        InsertBtn.setBackground(new java.awt.Color(102, 102, 102));
        InsertBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        InsertBtn.setForeground(new java.awt.Color(255, 255, 255));
        InsertBtn.setText("INSERT");
        InsertBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InsertBtnMouseClicked(evt);
            }
        });
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });
        InsertBtn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                InsertBtnKeyPressed(evt);
            }
        });

        AlterBtn.setBackground(new java.awt.Color(102, 102, 102));
        AlterBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AlterBtn.setForeground(new java.awt.Color(255, 255, 255));
        AlterBtn.setText("ALTER");
        AlterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(102, 102, 102));
        DeleteBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP2Layout = new javax.swing.GroupLayout(STEP2);
        STEP2.setLayout(STEP2Layout);
        STEP2Layout.setHorizontalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertBtn)
                .addGap(81, 81, 81)
                .addComponent(DeleteBtn)
                .addGap(81, 81, 81)
                .addComponent(AlterBtn)
                .addContainerGap())
        );
        STEP2Layout.setVerticalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBtn)
                    .addComponent(AlterBtn)
                    .addComponent(DeleteBtn))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        STEP3.setBackground(new java.awt.Color(51, 51, 51));
        STEP3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 3  (let's type)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PNAME.setBackground(new java.awt.Color(84, 84, 84));
        PNAME.setForeground(new java.awt.Color(204, 204, 204));
        PNAME.setText("PERSON NAME...");
        PNAME.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSON NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PNAMEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PNAMEFocusLost(evt);
            }
        });
        PNAME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PNAMEActionPerformed(evt);
            }
        });

        BIRTHDATE.setBackground(new java.awt.Color(84, 84, 84));
        BIRTHDATE.setForeground(new java.awt.Color(204, 204, 204));
        BIRTHDATE.setText("YYYY-MM-DD");
        BIRTHDATE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BIRTH DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        BIRTHDATE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BIRTHDATEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BIRTHDATEFocusLost(evt);
            }
        });
        BIRTHDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIRTHDATEActionPerformed(evt);
            }
        });

        SEX.setBackground(new java.awt.Color(84, 84, 84));
        SEX.setForeground(new java.awt.Color(204, 204, 204));
        SEX.setText("SEX...");
        SEX.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        SEX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SEXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SEXFocusLost(evt);
            }
        });
        SEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEXActionPerformed(evt);
            }
        });

        STUDENT_ID.setBackground(new java.awt.Color(84, 84, 84));
        STUDENT_ID.setForeground(new java.awt.Color(204, 204, 204));
        STUDENT_ID.setText("STUDENT ID...");
        STUDENT_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STUDENT ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        STUDENT_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                STUDENT_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                STUDENT_IDFocusLost(evt);
            }
        });
        STUDENT_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                STUDENT_IDActionPerformed(evt);
            }
        });

        grade.setBackground(new java.awt.Color(84, 84, 84));
        grade.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        grade.setForeground(new java.awt.Color(255, 255, 255));
        grade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "G" }));
        grade.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "GRADE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP3Layout = new javax.swing.GroupLayout(STEP3);
        STEP3.setLayout(STEP3Layout);
        STEP3Layout.setHorizontalGroup(
            STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addComponent(PNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BIRTHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SEX, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(STUDENT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(90, 90, 90)
                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        STEP3Layout.setVerticalGroup(
            STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP3Layout.createSequentialGroup()
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIRTHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
                    .addComponent(STUDENT_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RUN");
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        STEP5.setBackground(new java.awt.Color(51, 51, 51));
        STEP5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5), "OUTPUT ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout STEP5Layout = new javax.swing.GroupLayout(STEP5);
        STEP5.setLayout(STEP5Layout);
        STEP5Layout.setHorizontalGroup(
            STEP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP5Layout.setVerticalGroup(
            STEP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout STUDENT_PANELLayout = new javax.swing.GroupLayout(STUDENT_PANEL);
        STUDENT_PANEL.setLayout(STUDENT_PANELLayout);
        STUDENT_PANELLayout.setHorizontalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STUDENT_PANELLayout.createSequentialGroup()
                        .addComponent(STEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(STEP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(STEP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addComponent(STEP5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        STUDENT_PANELLayout.setVerticalGroup(
            STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, STUDENT_PANELLayout.createSequentialGroup()
                .addGroup(STUDENT_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(STEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(STEP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STUDENT_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(STEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(STEP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(STUDENT_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AlterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterBtnActionPerformed
        choise=3;
        PNAME.setText("PERSON NAME...");
        BIRTHDATE.setText("YYYY-MM-DD");
        SEX.setText("SEX...");
        STUDENT_ID.setText("STUDENT ID...");
        STUDENT_ID.setEditable(true);
        SEX.setEditable(true);
        BIRTHDATE.setEditable(true);
        PNAME.setEditable(true);        
        output.setText("YOU CHOSE ALTER!!! NOW GO TO STEP 3 \n");
    }//GEN-LAST:event_AlterBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        choise=2;
        PNAME.setEditable(false);
        PNAME.setText("not editable...");
        BIRTHDATE.setEditable(false);
        BIRTHDATE.setText("not editable...");
        SEX.setEditable(false);
        SEX.setText("not editable...");
        STUDENT_ID.setEditable(true);
        STUDENT_ID.setText("STUDENT ID...");
        output.setText("YOU CHOSE DELETE!!! NOW GO TO STEP 3 \n");
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        choise=1;
        PNAME.setText("PERSON NAME...");
        BIRTHDATE.setText("YYYY-MM-DD");
        SEX.setText("SEX...");
        STUDENT_ID.setEditable(false);
        STUDENT_ID.setText("not editable...");
        SEX.setEditable(true);
        BIRTHDATE.setEditable(true);
        PNAME.setEditable(true);     
        output.setText("YOU CHOSE INSERT!!! NOW GO TO STEP 3 \n");
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void CHOISEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOISEActionPerformed
        String choise=CHOISE.getSelectedItem().toString();
        TEACHER teacher = new TEACHER();
        STUDENT student = new STUDENT();
        if(choise.equals("TEACHER"))
        {
         teacher.setVisible(true);
         dispose();
        }
    }//GEN-LAST:event_CHOISEActionPerformed

    private void BIRTHDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIRTHDATEActionPerformed
        bdate=BIRTHDATE.getText();
    }//GEN-LAST:event_BIRTHDATEActionPerformed

    private void SEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEXActionPerformed
        sex=SEX.getText();
    }//GEN-LAST:event_SEXActionPerformed

    private void PNAMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PNAMEFocusGained
       if(PNAME.getText().equals("PERSON NAME...")){
          PNAME.setText("");
       }
    }//GEN-LAST:event_PNAMEFocusGained

    private void PNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PNAMEFocusLost
         if(PNAME.getText().equals("")){
          PNAME.setText("PERSON NAME...");
       }
    }//GEN-LAST:event_PNAMEFocusLost

    private void BIRTHDATEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BIRTHDATEFocusGained
       if(BIRTHDATE.getText().equals("YYYY-MM-DD")){
          BIRTHDATE.setText("");
       }
    }//GEN-LAST:event_BIRTHDATEFocusGained

    private void BIRTHDATEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BIRTHDATEFocusLost
         if(BIRTHDATE.getText().equals("")){
          BIRTHDATE.setText("YYYY-MM-DD");
       }
    }//GEN-LAST:event_BIRTHDATEFocusLost

    private void SEXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SEXFocusGained
        if(SEX.getText().equals("SEX...")){
          SEX.setText("");
       }
    }//GEN-LAST:event_SEXFocusGained

    private void SEXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SEXFocusLost
       if(SEX.getText().equals("")){
          SEX.setText("SEX...");
       }
    }//GEN-LAST:event_SEXFocusLost

    private void STUDENT_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STUDENT_IDFocusGained
        if(STUDENT_ID.getText().equals("STUDENT ID...")){
          STUDENT_ID.setText("");
       }
    }//GEN-LAST:event_STUDENT_IDFocusGained

    private void STUDENT_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_STUDENT_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_STUDENT_IDActionPerformed

    private void STUDENT_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_STUDENT_IDFocusLost
         if(STUDENT_ID.getText().equals("")){
          STUDENT_ID.setText("STUDENT ID...");
       }
    }//GEN-LAST:event_STUDENT_IDFocusLost

    private void PNAMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PNAMEActionPerformed
       name=PNAME.getText(); 
    }//GEN-LAST:event_PNAMEActionPerformed

    private void CoursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesBtnActionPerformed
        COURSES courses = new COURSES(); 
        courses.setVisible(true);
         dispose();
    }//GEN-LAST:event_CoursesBtnActionPerformed

    private void ExamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamBtnActionPerformed
        EXAM_RESULTS exam_res = new EXAM_RESULTS(); 
        exam_res.setVisible(true);
         dispose();
    }//GEN-LAST:event_ExamBtnActionPerformed

    private void TtoLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtoLBtnActionPerformed
        TEACHER_TO_LESSON teacher_to_lesson = new TEACHER_TO_LESSON(); 
        teacher_to_lesson.setVisible(true);
         dispose();
    }//GEN-LAST:event_TtoLBtnActionPerformed

    private void CompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompBtnActionPerformed
        COMPETITIONS competitions = new COMPETITIONS(); 
        competitions.setVisible(true);
         dispose();
    }//GEN-LAST:event_CompBtnActionPerformed

    private void QBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QBtnActionPerformed
        QUESTIONS questions = new QUESTIONS(); 
        questions.setVisible(true);
         dispose();
    }//GEN-LAST:event_QBtnActionPerformed

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        LOG log = new LOG(); 
        log.setVisible(true);
         dispose();
    }//GEN-LAST:event_LogBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int length = 0;
        
        try {
            length = TheProject.math_count();
        } catch (Exception ex) {
            Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        System.out.println(choise+" "+" to length : "+length);
        
           
           
        if(choise==1){
          
          bdate=BIRTHDATE.getText();
          sex=SEX.getText();
          name=PNAME.getText();
           try {
                TheProject.ypol_id();
                output.setText(TheProject.Student_in(name, bdate, sex, taxi));
            } catch (Exception ex) {
                Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
            }    
           
           
           try {
            length = TheProject.math_count();
        } catch (Exception ex) {
            Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
        }
           System.out.println(choise+" "+" to length : "+length+" to x einai "+x);
           
           
         choise=0;
       }
       else if(choise==2){  
        id=Integer.parseInt(STUDENT_ID.getText());
        choise=0;  
        ArrayList<String> list= new ArrayList<String>();
           try {
               list = TheProject.display_student();
           } catch (Exception ex) {
               Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
           }
            try {
                output.setText(TheProject.delete_student(id));
            } catch (Exception ex) {
                Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
            }
           
       length=length-1;
       }
       else if(choise==3){
        choise=0; 
        bdate=BIRTHDATE.getText();
        sex=SEX.getText();
        name=PNAME.getText();
        id=Integer.parseInt(STUDENT_ID.getText());
        ArrayList<String> list= new ArrayList<String>();
           try {
               list = TheProject.display_student();
           } catch (Exception ex) {
               Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
           }
           
            try {
                TheProject.Student_update(name, bdate, sex, id);
            } catch (Exception ex) {
                Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
            }
           output.setText("The ALTER is DONE!!! \n");
       
       }
       else{
           for(int i=0;i<99;i++){
             for(int j=0;j<=4;j++){
                    jTable.setValueAt("",i,j);
           }
           }
           System.out.println(choise+" "+"mpika gia emf  ");
           try {
               list = TheProject.display_student();
           } catch (Exception ex) {
               Logger.getLogger(STUDENT.class.getName()).log(Level.SEVERE, null, ex);
           }
          int k=0;
           for(int i=0;i<length;i++){
             for(int j=0;j<=4;j++){
                 if(list.get(k)!=null)
                    jTable.setValueAt(list.get(k).toString(),i,j);
                k=k+1;
           }
           }  
       }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void InsertBtnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_InsertBtnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertBtnKeyPressed

    private void InsertBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InsertBtnMouseClicked
        
    }//GEN-LAST:event_InsertBtnMouseClicked

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        taxi=(String)grade.getSelectedItem();
    }//GEN-LAST:event_gradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(STUDENT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new STUDENT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterBtn;
    private javax.swing.JTextField BIRTHDATE;
    private javax.swing.JComboBox<String> CHOISE;
    private javax.swing.JButton CompBtn;
    private javax.swing.JButton CoursesBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton ExamBtn;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JButton LogBtn;
    private javax.swing.JTextField PNAME;
    private javax.swing.JButton QBtn;
    private javax.swing.JTextField SEX;
    private javax.swing.JPanel STEP1;
    private javax.swing.JPanel STEP2;
    private javax.swing.JPanel STEP3;
    private javax.swing.JPanel STEP5;
    private javax.swing.JTextField STUDENT_ID;
    private javax.swing.JPanel STUDENT_PANEL;
    private javax.swing.JButton TtoLBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> grade;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private java.awt.TextArea output;
    // End of variables declaration//GEN-END:variables
}
