/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package theproject;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author monax
 */
public class TEACHER extends javax.swing.JFrame {
    ArrayList<String> list= new ArrayList<String>();
    /**
     * Creates new form TEACHER
     */
    public TEACHER() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TEACHER_PANEL = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PERSON = new javax.swing.JTable();
        STEP1 = new javax.swing.JPanel();
        CoursesBtn = new javax.swing.JButton();
        ExamBtn = new javax.swing.JButton();
        TtoLBtn = new javax.swing.JButton();
        CompBtn = new javax.swing.JButton();
        CHOISE = new javax.swing.JComboBox<>();
        QBtn = new javax.swing.JButton();
        LogBtn = new javax.swing.JButton();
        STEP2 = new javax.swing.JPanel();
        InsertBtn = new javax.swing.JButton();
        AlterBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        STEP3 = new javax.swing.JPanel();
        PNAME = new javax.swing.JTextField();
        SEX = new javax.swing.JTextField();
        TEACHER_ID = new javax.swing.JTextField();
        SALARY = new javax.swing.JTextField();
        BIRTHDATE = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        STEP5 = new javax.swing.JPanel();
        output = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TEACHER_PANEL.setBackground(new java.awt.Color(51, 51, 51));

        PERSON.setBackground(new java.awt.Color(204, 204, 204));
        PERSON.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PERSON NAME", "BIRTHDAY", "SEX", "TEACHER ID", "SALARY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(PERSON);

        STEP1.setBackground(new java.awt.Color(51, 51, 51));
        STEP1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP  1   (choose table)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 19), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        CoursesBtn.setBackground(new java.awt.Color(102, 102, 102));
        CoursesBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CoursesBtn.setForeground(new java.awt.Color(255, 255, 255));
        CoursesBtn.setText("COURSES");
        CoursesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CoursesBtnActionPerformed(evt);
            }
        });

        ExamBtn.setBackground(new java.awt.Color(102, 102, 102));
        ExamBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        ExamBtn.setForeground(new java.awt.Color(255, 255, 255));
        ExamBtn.setText("EXAM RESULTS");
        ExamBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExamBtnActionPerformed(evt);
            }
        });

        TtoLBtn.setBackground(new java.awt.Color(102, 102, 102));
        TtoLBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        TtoLBtn.setForeground(new java.awt.Color(255, 255, 255));
        TtoLBtn.setText("TEACHER TO LESSON");
        TtoLBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TtoLBtnActionPerformed(evt);
            }
        });

        CompBtn.setBackground(new java.awt.Color(102, 102, 102));
        CompBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CompBtn.setForeground(new java.awt.Color(255, 255, 255));
        CompBtn.setText("COMPETITIONS");
        CompBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CompBtnActionPerformed(evt);
            }
        });

        CHOISE.setBackground(new java.awt.Color(102, 102, 102));
        CHOISE.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        CHOISE.setForeground(new java.awt.Color(255, 255, 255));
        CHOISE.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TEACHER", "STUDENT" }));
        CHOISE.setAlignmentX(CENTER_ALIGNMENT);
        CHOISE.setAlignmentY(CENTER_ALIGNMENT);
        CHOISE.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CHOISE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CHOISEActionPerformed(evt);
            }
        });

        QBtn.setBackground(new java.awt.Color(102, 102, 102));
        QBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        QBtn.setForeground(new java.awt.Color(255, 255, 255));
        QBtn.setText("QUESTIONS");
        QBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                QBtnActionPerformed(evt);
            }
        });

        LogBtn.setBackground(new java.awt.Color(102, 102, 102));
        LogBtn.setFont(new java.awt.Font("Gadugi", 1, 24)); // NOI18N
        LogBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogBtn.setText("LOG");
        LogBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP1Layout = new javax.swing.GroupLayout(STEP1);
        STEP1.setLayout(STEP1Layout);
        STEP1Layout.setHorizontalGroup(
            STEP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CoursesBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ExamBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(TtoLBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CHOISE, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(CompBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(QBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LogBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP1Layout.setVerticalGroup(
            STEP1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP1Layout.createSequentialGroup()
                .addComponent(CHOISE, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CoursesBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ExamBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(TtoLBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(CompBtn)
                .addGap(0, 0, 0)
                .addComponent(QBtn)
                .addGap(0, 0, 0)
                .addComponent(LogBtn)
                .addGap(0, 0, 0))
        );

        STEP2.setBackground(new java.awt.Color(51, 51, 51));
        STEP2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 2   (choose action)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        InsertBtn.setBackground(new java.awt.Color(102, 102, 102));
        InsertBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        InsertBtn.setForeground(new java.awt.Color(255, 255, 255));
        InsertBtn.setText("INSERT");
        InsertBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertBtnActionPerformed(evt);
            }
        });

        AlterBtn.setBackground(new java.awt.Color(102, 102, 102));
        AlterBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        AlterBtn.setForeground(new java.awt.Color(255, 255, 255));
        AlterBtn.setText("ALTER");
        AlterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setBackground(new java.awt.Color(102, 102, 102));
        DeleteBtn.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        DeleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        DeleteBtn.setText("DELETE");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP2Layout = new javax.swing.GroupLayout(STEP2);
        STEP2.setLayout(STEP2Layout);
        STEP2Layout.setHorizontalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(InsertBtn)
                .addGap(81, 81, 81)
                .addComponent(DeleteBtn)
                .addGap(81, 81, 81)
                .addComponent(AlterBtn)
                .addContainerGap())
        );
        STEP2Layout.setVerticalGroup(
            STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP2Layout.createSequentialGroup()
                .addGroup(STEP2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertBtn)
                    .addComponent(AlterBtn)
                    .addComponent(DeleteBtn))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        STEP3.setBackground(new java.awt.Color(51, 51, 51));
        STEP3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "STEP 3  (let's type)", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        PNAME.setBackground(new java.awt.Color(84, 84, 84));
        PNAME.setForeground(new java.awt.Color(204, 204, 204));
        PNAME.setText("PERSON NAME...");
        PNAME.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PERSON NAME", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        PNAME.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                PNAMEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                PNAMEFocusLost(evt);
            }
        });

        SEX.setBackground(new java.awt.Color(84, 84, 84));
        SEX.setForeground(new java.awt.Color(204, 204, 204));
        SEX.setText("SEX...");
        SEX.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "SEX", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        SEX.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SEXFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SEXFocusLost(evt);
            }
        });
        SEX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SEXActionPerformed(evt);
            }
        });

        TEACHER_ID.setBackground(new java.awt.Color(84, 84, 84));
        TEACHER_ID.setForeground(new java.awt.Color(204, 204, 204));
        TEACHER_ID.setText("TEACHER ID...");
        TEACHER_ID.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "TEACHER ID", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        TEACHER_ID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                TEACHER_IDFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                TEACHER_IDFocusLost(evt);
            }
        });
        TEACHER_ID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TEACHER_IDActionPerformed(evt);
            }
        });

        SALARY.setBackground(new java.awt.Color(84, 84, 84));
        SALARY.setForeground(new java.awt.Color(204, 204, 204));
        SALARY.setText("SALARY...");
        SALARY.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "M.O", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        SALARY.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                SALARYFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                SALARYFocusLost(evt);
            }
        });

        BIRTHDATE.setBackground(new java.awt.Color(84, 84, 84));
        BIRTHDATE.setForeground(new java.awt.Color(204, 204, 204));
        BIRTHDATE.setText("YYYY-MM-DD");
        BIRTHDATE.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "BIRTH DATE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Bahnschrift", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        BIRTHDATE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                BIRTHDATEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                BIRTHDATEFocusLost(evt);
            }
        });
        BIRTHDATE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BIRTHDATEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout STEP3Layout = new javax.swing.GroupLayout(STEP3);
        STEP3.setLayout(STEP3Layout);
        STEP3Layout.setHorizontalGroup(
            STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addComponent(PNAME, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(BIRTHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(SEX, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(STEP3Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(TEACHER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(SALARY, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(11, 11, 11))
        );
        STEP3Layout.setVerticalGroup(
            STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(STEP3Layout.createSequentialGroup()
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SEX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BIRTHDATE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(STEP3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TEACHER_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALARY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("RUN");
        jButton1.setAlignmentY(1.0F);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        STEP5.setBackground(new java.awt.Color(51, 51, 51));
        STEP5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 5), "OUTPUT ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Bahnschrift", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        STEP5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout STEP5Layout = new javax.swing.GroupLayout(STEP5);
        STEP5.setLayout(STEP5Layout);
        STEP5Layout.setHorizontalGroup(
            STEP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        STEP5Layout.setVerticalGroup(
            STEP5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(output, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout TEACHER_PANELLayout = new javax.swing.GroupLayout(TEACHER_PANEL);
        TEACHER_PANEL.setLayout(TEACHER_PANELLayout);
        TEACHER_PANELLayout.setHorizontalGroup(
            TEACHER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TEACHER_PANELLayout.createSequentialGroup()
                .addComponent(STEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(TEACHER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TEACHER_PANELLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(TEACHER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(STEP2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(STEP3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(TEACHER_PANELLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(TEACHER_PANELLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(TEACHER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(STEP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        TEACHER_PANELLayout.setVerticalGroup(
            TEACHER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TEACHER_PANELLayout.createSequentialGroup()
                .addGroup(TEACHER_PANELLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(TEACHER_PANELLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(STEP2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(STEP3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(TEACHER_PANELLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(STEP1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(STEP5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(TEACHER_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TEACHER_PANEL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CHOISEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CHOISEActionPerformed
        String choise=CHOISE.getSelectedItem().toString();
        STUDENT student = new STUDENT();
        if(choise.equals("STUDENT"))
        {
         student.setVisible(true);
         dispose();
        }  
    }//GEN-LAST:event_CHOISEActionPerformed

    private void InsertBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InsertBtnActionPerformed

    private void AlterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DeleteBtnActionPerformed

    private void PNAMEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PNAMEFocusGained
        if(PNAME.getText().equals("PERSON NAME...")){
            PNAME.setText("");
        }
    }//GEN-LAST:event_PNAMEFocusGained

    private void PNAMEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_PNAMEFocusLost
        if(PNAME.getText().equals("")){
            PNAME.setText("PERSON NAME...");
        }
    }//GEN-LAST:event_PNAMEFocusLost

    private void SEXFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SEXFocusGained
        if(SEX.getText().equals("SEX...")){
            SEX.setText("");
        }
    }//GEN-LAST:event_SEXFocusGained

    private void SEXFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SEXFocusLost
        if(SEX.getText().equals("")){
            SEX.setText("SEX...");
        }
    }//GEN-LAST:event_SEXFocusLost

    private void SEXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SEXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SEXActionPerformed

    private void TEACHER_IDFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEACHER_IDFocusGained
        if(TEACHER_ID.getText().equals("TEACHER ID...")){
            TEACHER_ID.setText("");
        }
    }//GEN-LAST:event_TEACHER_IDFocusGained

    private void TEACHER_IDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TEACHER_IDFocusLost
        if(TEACHER_ID.getText().equals("")){
            TEACHER_ID.setText("TEACHER ID...");
        }
    }//GEN-LAST:event_TEACHER_IDFocusLost

    private void TEACHER_IDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TEACHER_IDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TEACHER_IDActionPerformed

    private void SALARYFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SALARYFocusGained
        if(SALARY.getText().equals("SALARY...")){
            SALARY.setText("");
        }
    }//GEN-LAST:event_SALARYFocusGained

    private void SALARYFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_SALARYFocusLost
        if(SALARY.getText().equals("")){
            SALARY.setText("SALARY...");
        }
    }//GEN-LAST:event_SALARYFocusLost

    private void CoursesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CoursesBtnActionPerformed
        COURSES courses = new COURSES(); 
        courses.setVisible(true);
         dispose();
    }//GEN-LAST:event_CoursesBtnActionPerformed

    private void ExamBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExamBtnActionPerformed
        EXAM_RESULTS exam_res = new EXAM_RESULTS(); 
        exam_res.setVisible(true);
         dispose();
    }//GEN-LAST:event_ExamBtnActionPerformed

    private void TtoLBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TtoLBtnActionPerformed
        TEACHER_TO_LESSON teacher_to_lesson = new TEACHER_TO_LESSON(); 
        teacher_to_lesson.setVisible(true);
         dispose();
    }//GEN-LAST:event_TtoLBtnActionPerformed

    private void CompBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CompBtnActionPerformed
        COMPETITIONS competitions = new COMPETITIONS(); 
        competitions.setVisible(true);
         dispose();
    }//GEN-LAST:event_CompBtnActionPerformed

    private void QBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_QBtnActionPerformed
        QUESTIONS questions = new QUESTIONS();
        questions.setVisible(true);
        dispose();
    }//GEN-LAST:event_QBtnActionPerformed

    private void LogBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogBtnActionPerformed
        LOG log = new LOG();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_LogBtnActionPerformed

    private void BIRTHDATEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BIRTHDATEFocusGained
        if(BIRTHDATE.getText().equals("YYYY-MM-DD")){
            BIRTHDATE.setText("");
        }
    }//GEN-LAST:event_BIRTHDATEFocusGained

    private void BIRTHDATEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_BIRTHDATEFocusLost
        if(BIRTHDATE.getText().equals("")){
            BIRTHDATE.setText("YYYY-MM-DD");
        }
    }//GEN-LAST:event_BIRTHDATEFocusLost

    private void BIRTHDATEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BIRTHDATEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BIRTHDATEActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        for(int i=0;i<99;i++){
             for(int j=0;j<=4;j++){
                    PERSON.setValueAt("",i,j);
           }
           }
           try {
               list = TheProject.display_teacher();
           } catch (Exception ex) {
               Logger.getLogger(TEACHER.class.getName()).log(Level.SEVERE, null, ex);
           }
          int k=0;
           for(int i=0;i<7;i++){
             for(int j=0;j<=4;j++){
                 if(list.get(k)!=null)
                    PERSON.setValueAt(list.get(k).toString(),i,j);
                k=k+1;
           }
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TEACHER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TEACHER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterBtn;
    private javax.swing.JTextField BIRTHDATE;
    private javax.swing.JComboBox<String> CHOISE;
    private javax.swing.JButton CompBtn;
    private javax.swing.JButton CoursesBtn;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton ExamBtn;
    private javax.swing.JButton InsertBtn;
    private javax.swing.JButton LogBtn;
    private javax.swing.JTable PERSON;
    private javax.swing.JTextField PNAME;
    private javax.swing.JButton QBtn;
    private javax.swing.JTextField SALARY;
    private javax.swing.JTextField SEX;
    private javax.swing.JPanel STEP1;
    private javax.swing.JPanel STEP2;
    private javax.swing.JPanel STEP3;
    private javax.swing.JPanel STEP5;
    private javax.swing.JTextField TEACHER_ID;
    private javax.swing.JPanel TEACHER_PANEL;
    private javax.swing.JButton TtoLBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.TextArea output;
    // End of variables declaration//GEN-END:variables
}
